// Auto-generated 2026-09-10 08:49 UTC
window.CLUBFOOTBALL_DATA = {
  "UPDATED": "2026-09-10 08:49 UTC",
  "SEASON": "UEFA Champions League 2026-27 · Fase liga",
  "FORMULA": "ΔElo = 25 × G × (resultado − esperado) · +65 en casa · G: ×1 / ×1,5 / ×1,75+ por margen",
  "SOURCE": {
    "name": "Elo propio (semilla ClubElo congelada a inicio de temporada) + resultados y alineaciones de ESPN",
    "note": "Solo mueven el Elo los partidos de Champions entre los 36. Jugadores: ΔElo del equipo × minutos/90, simétrico."
  },
  "ELO_RANKING": [
    {
      "rank": 1,
      "name": "Arsenal",
      "fullName": "Arsenal",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
      "elo": 2047,
      "seed": 2039,
      "delta": 7.7,
      "lastDelta": 7.7,
      "played": 1
    },
    {
      "rank": 2,
      "name": "Bayern",
      "fullName": "Bayern Munich",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
      "elo": 2043,
      "seed": 2043,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 3,
      "name": "Man City",
      "fullName": "Manchester City",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
      "elo": 2040,
      "seed": 2028,
      "delta": 11.7,
      "lastDelta": 11.7,
      "played": 1
    },
    {
      "rank": 4,
      "name": "Real Madrid",
      "fullName": "Real Madrid",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
      "elo": 1982,
      "seed": 1973,
      "delta": 9.2,
      "lastDelta": 9.2,
      "played": 1
    },
    {
      "rank": 5,
      "name": "Inter Milan",
      "fullName": "Internazionale",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
      "elo": 1935,
      "seed": 1944,
      "delta": -9.2,
      "lastDelta": -9.2,
      "played": 1
    },
    {
      "rank": 6,
      "name": "Aston Villa",
      "fullName": "Aston Villa",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
      "elo": 1903,
      "seed": 1891,
      "delta": 11.6,
      "lastDelta": 11.6,
      "played": 1
    },
    {
      "rank": 7,
      "name": "Dortmund",
      "fullName": "Borussia Dortmund",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
      "elo": 1902,
      "seed": 1895,
      "delta": 7.0,
      "lastDelta": 7.0,
      "played": 1
    },
    {
      "rank": 8,
      "name": "Sporting",
      "fullName": "Sporting CP",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
      "elo": 1893,
      "seed": 1881,
      "delta": 11.5,
      "lastDelta": 11.5,
      "played": 1
    },
    {
      "rank": 9,
      "name": "Man United",
      "fullName": "Manchester United",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
      "elo": 1886,
      "seed": 1886,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 10,
      "name": "Atlético",
      "fullName": "Atlético Madrid",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
      "elo": 1868,
      "seed": 1888,
      "delta": -19.7,
      "lastDelta": -19.7,
      "played": 1
    },
    {
      "rank": 11,
      "name": "AS Roma",
      "fullName": "AS Roma",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
      "elo": 1851,
      "seed": 1851,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 12,
      "name": "Stuttgart",
      "fullName": "VfB Stuttgart",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
      "elo": 1840,
      "seed": 1831,
      "delta": 8.7,
      "lastDelta": 8.7,
      "played": 1
    },
    {
      "rank": 13,
      "name": "RB Leipzig",
      "fullName": "RB Leipzig",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
      "elo": 1827,
      "seed": 1827,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 14,
      "name": "Betis",
      "fullName": "Real Betis",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "elo": 1825,
      "seed": 1811,
      "delta": 13.8,
      "lastDelta": 13.8,
      "played": 1
    },
    {
      "rank": 15,
      "name": "Napoli",
      "fullName": "Napoli",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
      "elo": 1824,
      "seed": 1832,
      "delta": -7.7,
      "lastDelta": -7.7,
      "played": 1
    },
    {
      "rank": 16,
      "name": "Lens",
      "fullName": "Lens",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
      "elo": 1815,
      "seed": 1815,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 17,
      "name": "FC Porto",
      "fullName": "FC Porto",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
      "elo": 1814,
      "seed": 1826,
      "delta": -11.7,
      "lastDelta": -11.7,
      "played": 1
    },
    {
      "rank": 18,
      "name": "Como",
      "fullName": "Como",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
      "elo": 1807,
      "seed": 1807,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 19,
      "name": "PSV",
      "fullName": "PSV Eindhoven",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
      "elo": 1794,
      "seed": 1794,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 20,
      "name": "Galatasaray",
      "fullName": "Galatasaray",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
      "elo": 1793,
      "seed": 1805,
      "delta": -11.5,
      "lastDelta": -11.5,
      "played": 1
    },
    {
      "rank": 21,
      "name": "Club Brugge",
      "fullName": "Club Brugge",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
      "elo": 1790,
      "seed": 1802,
      "delta": -11.6,
      "lastDelta": -11.6,
      "played": 1
    },
    {
      "rank": 22,
      "name": "Bodo/Glimt",
      "fullName": "Bodo/Glimt",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
      "elo": 1789,
      "seed": 1789,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 23,
      "name": "Villarreal",
      "fullName": "Villarreal",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
      "elo": 1788,
      "seed": 1795,
      "delta": -7.0,
      "lastDelta": -7.0,
      "played": 1
    },
    {
      "rank": 24,
      "name": "Fenerbahce",
      "fullName": "Fenerbahce",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
      "elo": 1778,
      "seed": 1778,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 25,
      "name": "Lille",
      "fullName": "Lille",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
      "elo": 1769,
      "seed": 1783,
      "delta": -13.8,
      "lastDelta": -13.8,
      "played": 1
    },
    {
      "rank": 26,
      "name": "Slavia Prague",
      "fullName": "Slavia Prague",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
      "elo": 1763,
      "seed": 1763,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 27,
      "name": "AEK Athens",
      "fullName": "AEK Athens",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/887.png",
      "elo": 1715,
      "seed": 1707,
      "delta": 8.1,
      "lastDelta": 8.1,
      "played": 1
    },
    {
      "rank": 28,
      "name": "PSG",
      "fullName": "Paris Saint-Germain",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
      "elo": 1710,
      "seed": 1698,
      "delta": 11.6,
      "lastDelta": 11.6,
      "played": 1
    },
    {
      "rank": 29,
      "name": "Feyenoord",
      "fullName": "Feyenoord Rotterdam",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
      "elo": 1685,
      "seed": 1708,
      "delta": -23.2,
      "lastDelta": -23.2,
      "played": 1
    },
    {
      "rank": 30,
      "name": "Shakhtar",
      "fullName": "Shakhtar Donetsk",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
      "elo": 1681,
      "seed": 1681,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    },
    {
      "rank": 31,
      "name": "Viking FK",
      "fullName": "Viking FK",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png",
      "elo": 1678,
      "seed": 1687,
      "delta": -8.7,
      "lastDelta": -8.7,
      "played": 1
    },
    {
      "rank": 32,
      "name": "Barcelona",
      "fullName": "Barcelona",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "elo": 1670,
      "seed": 1647,
      "delta": 23.2,
      "lastDelta": 23.2,
      "played": 1
    },
    {
      "rank": 33,
      "name": "LASK Linz",
      "fullName": "LASK Linz",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
      "elo": 1636,
      "seed": 1644,
      "delta": -8.1,
      "lastDelta": -8.1,
      "played": 1
    },
    {
      "rank": 34,
      "name": "Liverpool",
      "fullName": "Liverpool",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "elo": 1616,
      "seed": 1596,
      "delta": 19.7,
      "lastDelta": 19.7,
      "played": 1
    },
    {
      "rank": 35,
      "name": "S Bratislava",
      "fullName": "Slovan Bratislava",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
      "elo": 1543,
      "seed": 1555,
      "delta": -11.6,
      "lastDelta": -11.6,
      "played": 1
    },
    {
      "rank": 36,
      "name": "Sabah",
      "fullName": "Sabah FK",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
      "elo": 1500,
      "seed": 1500,
      "delta": 0.0,
      "lastDelta": null,
      "played": 0
    }
  ],
  "STANDINGS": [
    {
      "id": "160",
      "name": "Paris Saint-Germain",
      "shortName": "PSG",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 6,
      "ga": 1,
      "gd": 5,
      "points": 3,
      "rank": 1,
      "pos": 1
    },
    {
      "id": "83",
      "name": "Barcelona",
      "shortName": "Barcelona",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 5,
      "ga": 1,
      "gd": 4,
      "points": 3,
      "rank": 2,
      "pos": 2
    },
    {
      "id": "2250",
      "name": "Sporting CP",
      "shortName": "Sporting",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 3,
      "ga": 1,
      "gd": 2,
      "points": 3,
      "rank": 3,
      "pos": 3
    },
    {
      "id": "134",
      "name": "VfB Stuttgart",
      "shortName": "Stuttgart",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 3,
      "ga": 1,
      "gd": 2,
      "points": 3,
      "rank": 4,
      "pos": 4
    },
    {
      "id": "382",
      "name": "Manchester City",
      "shortName": "Man City",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 2,
      "ga": 0,
      "gd": 2,
      "points": 3,
      "rank": 5,
      "pos": 5
    },
    {
      "id": "362",
      "name": "Aston Villa",
      "shortName": "Aston Villa",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 3,
      "ga": 2,
      "gd": 1,
      "points": 3,
      "rank": 6,
      "pos": 6
    },
    {
      "id": "244",
      "name": "Real Betis",
      "shortName": "Betis",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 3,
      "ga": 2,
      "gd": 1,
      "points": 3,
      "rank": 7,
      "pos": 7
    },
    {
      "id": "124",
      "name": "Borussia Dortmund",
      "shortName": "Dortmund",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 3,
      "ga": 2,
      "gd": 1,
      "points": 3,
      "rank": 8,
      "pos": 8
    },
    {
      "id": "364",
      "name": "Liverpool",
      "shortName": "Liverpool",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 2,
      "ga": 1,
      "gd": 1,
      "points": 3,
      "rank": 9,
      "pos": 9
    },
    {
      "id": "86",
      "name": "Real Madrid",
      "shortName": "Real Madrid",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 2,
      "ga": 1,
      "gd": 1,
      "points": 3,
      "rank": 10,
      "pos": 10
    },
    {
      "id": "359",
      "name": "Arsenal",
      "shortName": "Arsenal",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 1,
      "ga": 0,
      "gd": 1,
      "points": 3,
      "rank": 11,
      "pos": 11
    },
    {
      "id": "887",
      "name": "AEK Athens",
      "shortName": "AEK Athens",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/887.png",
      "played": 1,
      "won": 1,
      "drawn": 0,
      "lost": 0,
      "gf": 1,
      "ga": 0,
      "gd": 1,
      "points": 3,
      "rank": 12,
      "pos": 12
    },
    {
      "id": "132",
      "name": "Bayern Munich",
      "shortName": "Bayern",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 13,
      "pos": 13
    },
    {
      "id": "2980",
      "name": "Bodo/Glimt",
      "shortName": "Bodo/Glimt",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 14,
      "pos": 14
    },
    {
      "id": "2572",
      "name": "Como",
      "shortName": "Como",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 15,
      "pos": 15
    },
    {
      "id": "436",
      "name": "Fenerbahce",
      "shortName": "Fenerbahce",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 16,
      "pos": 16
    },
    {
      "id": "175",
      "name": "Lens",
      "shortName": "Lens",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 17,
      "pos": 17
    },
    {
      "id": "360",
      "name": "Manchester United",
      "shortName": "Man United",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 18,
      "pos": 18
    },
    {
      "id": "148",
      "name": "PSV Eindhoven",
      "shortName": "PSV",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 19,
      "pos": 19
    },
    {
      "id": "11420",
      "name": "RB Leipzig",
      "shortName": "RB Leipzig",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 20,
      "pos": 20
    },
    {
      "id": "104",
      "name": "AS Roma",
      "shortName": "AS Roma",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 21,
      "pos": 21
    },
    {
      "id": "21922",
      "name": "Sabah FK",
      "shortName": "Sabah",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 22,
      "pos": 22
    },
    {
      "id": "493",
      "name": "Shakhtar Donetsk",
      "shortName": "Shakhtar",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 23,
      "pos": 23
    },
    {
      "id": "494",
      "name": "Slavia Prague",
      "shortName": "Slavia Prague",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
      "played": 0,
      "won": 0,
      "drawn": 0,
      "lost": 0,
      "gf": 0,
      "ga": 0,
      "gd": 0,
      "points": 0,
      "rank": 24,
      "pos": 24
    },
    {
      "id": "102",
      "name": "Villarreal",
      "shortName": "Villarreal",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 2,
      "ga": 3,
      "gd": -1,
      "points": 0,
      "rank": 25,
      "pos": 25
    },
    {
      "id": "570",
      "name": "Club Brugge",
      "shortName": "Club Brugge",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 2,
      "ga": 3,
      "gd": -1,
      "points": 0,
      "rank": 26,
      "pos": 26
    },
    {
      "id": "166",
      "name": "Lille",
      "shortName": "Lille",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 2,
      "ga": 3,
      "gd": -1,
      "points": 0,
      "rank": 27,
      "pos": 27
    },
    {
      "id": "1068",
      "name": "Atlético Madrid",
      "shortName": "Atlético",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 1,
      "ga": 2,
      "gd": -1,
      "points": 0,
      "rank": 28,
      "pos": 28
    },
    {
      "id": "110",
      "name": "Internazionale",
      "shortName": "Inter Milan",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 1,
      "ga": 2,
      "gd": -1,
      "points": 0,
      "rank": 29,
      "pos": 29
    },
    {
      "id": "4411",
      "name": "LASK Linz",
      "shortName": "LASK Linz",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 0,
      "ga": 1,
      "gd": -1,
      "points": 0,
      "rank": 30,
      "pos": 30
    },
    {
      "id": "114",
      "name": "Napoli",
      "shortName": "Napoli",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 0,
      "ga": 1,
      "gd": -1,
      "points": 0,
      "rank": 31,
      "pos": 31
    },
    {
      "id": "432",
      "name": "Galatasaray",
      "shortName": "Galatasaray",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 1,
      "ga": 3,
      "gd": -2,
      "points": 0,
      "rank": 32,
      "pos": 32
    },
    {
      "id": "510",
      "name": "Viking FK",
      "shortName": "Viking FK",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 1,
      "ga": 3,
      "gd": -2,
      "points": 0,
      "rank": 33,
      "pos": 33
    },
    {
      "id": "437",
      "name": "FC Porto",
      "shortName": "FC Porto",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 0,
      "ga": 2,
      "gd": -2,
      "points": 0,
      "rank": 34,
      "pos": 34
    },
    {
      "id": "142",
      "name": "Feyenoord Rotterdam",
      "shortName": "Feyenoord",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 1,
      "ga": 5,
      "gd": -4,
      "points": 0,
      "rank": 35,
      "pos": 35
    },
    {
      "id": "521",
      "name": "Slovan Bratislava",
      "shortName": "S Bratislava",
      "logo": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
      "played": 1,
      "won": 0,
      "drawn": 0,
      "lost": 1,
      "gf": 1,
      "ga": 6,
      "gd": -5,
      "points": 0,
      "rank": 36,
      "pos": 36
    }
  ],
  "MATCHES_RECENT": [
    {
      "id": "401915447",
      "date": "2026-09-09T19:00Z",
      "home": "Sporting",
      "away": "Galatasaray",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
      "score": "3-1",
      "deltaHome": 11.5,
      "deltaAway": -11.5,
      "expHome": 69
    },
    {
      "id": "401915445",
      "date": "2026-09-09T19:00Z",
      "home": "PSG",
      "away": "S Bratislava",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/521.png",
      "score": "6-1",
      "deltaHome": 11.6,
      "deltaAway": -11.6,
      "expHome": 77
    },
    {
      "id": "401915423",
      "date": "2026-09-09T19:00Z",
      "home": "Napoli",
      "away": "Arsenal",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
      "score": "0-1",
      "deltaHome": -7.7,
      "deltaAway": 7.7,
      "expHome": 31
    },
    {
      "id": "401915446",
      "date": "2026-09-09T19:00Z",
      "home": "Liverpool",
      "away": "Atlético",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
      "score": "2-1",
      "deltaHome": 19.7,
      "deltaAway": -19.7,
      "expHome": 21
    },
    {
      "id": "401915448",
      "date": "2026-09-09T16:45Z",
      "home": "Stuttgart",
      "away": "Viking FK",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png",
      "score": "3-1",
      "deltaHome": 8.7,
      "deltaAway": -8.7,
      "expHome": 77
    },
    {
      "id": "401915424",
      "date": "2026-09-09T16:45Z",
      "home": "Barcelona",
      "away": "Feyenoord",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
      "score": "5-1",
      "deltaHome": 23.2,
      "deltaAway": -23.2,
      "expHome": 51
    },
    {
      "id": "401915451",
      "date": "2026-09-08T19:00Z",
      "home": "Real Madrid",
      "away": "Inter Milan",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
      "score": "2-1",
      "deltaHome": 9.2,
      "deltaAway": -9.2,
      "expHome": 63
    },
    {
      "id": "401915450",
      "date": "2026-09-08T19:00Z",
      "home": "Lille",
      "away": "Betis",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "score": "2-3",
      "deltaHome": -13.8,
      "deltaAway": 13.8,
      "expHome": 55
    },
    {
      "id": "401915425",
      "date": "2026-09-08T19:00Z",
      "home": "FC Porto",
      "away": "Man City",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
      "score": "0-2",
      "deltaHome": -11.7,
      "deltaAway": 11.7,
      "expHome": 31
    },
    {
      "id": "401915449",
      "date": "2026-09-08T19:00Z",
      "home": "Dortmund",
      "away": "Villarreal",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
      "score": "3-2",
      "deltaHome": 7.0,
      "deltaAway": -7.0,
      "expHome": 72
    },
    {
      "id": "401915426",
      "date": "2026-09-08T16:45Z",
      "home": "Club Brugge",
      "away": "Aston Villa",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
      "score": "2-3",
      "deltaHome": -11.6,
      "deltaAway": 11.6,
      "expHome": 47
    },
    {
      "id": "401915452",
      "date": "2026-09-08T16:45Z",
      "home": "AEK Athens",
      "away": "LASK Linz",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/887.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
      "score": "1-0",
      "deltaHome": 8.1,
      "deltaAway": -8.1,
      "expHome": 68
    }
  ],
  "MATCHES_UPCOMING": [
    {
      "id": "401915444",
      "date": "2026-09-10T16:45Z",
      "home": "Fenerbahce",
      "away": "AS Roma",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
      "expHome": 49
    },
    {
      "id": "401915422",
      "date": "2026-09-10T16:45Z",
      "home": "PSV",
      "away": "Shakhtar",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/493.png",
      "expHome": 74
    },
    {
      "id": "401915443",
      "date": "2026-09-10T19:00Z",
      "home": "Bayern",
      "away": "Bodo/Glimt",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/2980.png",
      "expHome": 86
    },
    {
      "id": "401915441",
      "date": "2026-09-10T19:00Z",
      "home": "Como",
      "away": "RB Leipzig",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
      "expHome": 56
    },
    {
      "id": "401915442",
      "date": "2026-09-10T19:00Z",
      "home": "Man United",
      "away": "Sabah",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
      "expHome": 93
    },
    {
      "id": "401915440",
      "date": "2026-09-10T19:00Z",
      "home": "Slavia Prague",
      "away": "Lens",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
      "expHome": 52
    },
    {
      "id": "401915418",
      "date": "2026-10-13T16:45Z",
      "home": "Lens",
      "away": "Sporting",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/175.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/2250.png",
      "expHome": 48
    },
    {
      "id": "401915436",
      "date": "2026-10-13T16:45Z",
      "home": "Sabah",
      "away": "Slavia Prague",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/21922.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/494.png",
      "expHome": 24
    },
    {
      "id": "401915417",
      "date": "2026-10-13T19:00Z",
      "home": "Arsenal",
      "away": "Lille",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
      "expHome": 88
    },
    {
      "id": "401915412",
      "date": "2026-10-13T19:00Z",
      "home": "Atlético",
      "away": "Man United",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
      "expHome": 57
    },
    {
      "id": "401915435",
      "date": "2026-10-13T19:00Z",
      "home": "Galatasaray",
      "away": "Barcelona",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/432.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "expHome": 75
    },
    {
      "id": "401915413",
      "date": "2026-10-13T19:00Z",
      "home": "Inter Milan",
      "away": "Club Brugge",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/570.png",
      "expHome": 77
    },
    {
      "id": "401915434",
      "date": "2026-10-13T19:00Z",
      "home": "RB Leipzig",
      "away": "PSV",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
      "expHome": 64
    },
    {
      "id": "401915411",
      "date": "2026-10-13T19:00Z",
      "home": "Viking FK",
      "away": "Bayern",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/510.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
      "expHome": 15
    },
    {
      "id": "401915410",
      "date": "2026-10-13T19:00Z",
      "home": "Villarreal",
      "away": "Napoli",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
      "expHome": 54
    },
    {
      "id": "401915416",
      "date": "2026-10-14T16:45Z",
      "home": "Feyenoord",
      "away": "Como",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/2572.png",
      "expHome": 42
    },
    {
      "id": "401915415",
      "date": "2026-10-14T16:45Z",
      "home": "LASK Linz",
      "away": "Liverpool",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/4411.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "expHome": 62
    },
    {
      "id": "401915414",
      "date": "2026-10-14T19:00Z",
      "home": "AS Roma",
      "away": "Real Madrid",
      "homeLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
      "awayLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
      "expHome": 41
    }
  ],
  "PLAYER_RANKING": [
    {
      "rank": 1,
      "name": "Joan García",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 2,
      "name": "Andreas Christensen",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 3,
      "name": "Pau Cubarsí",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 4,
      "name": "João Cancelo",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 5,
      "name": "Jules Koundé",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 6,
      "name": "Rodri",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 7,
      "name": "Pedri",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 8,
      "name": "Dani Olmo",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 9,
      "name": "Raphinha",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 10,
      "name": "Karim Adeyemi",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 11,
      "name": "Lamine Yamal",
      "team": "Barcelona",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
      "delta": 23.2,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 12,
      "name": "Alisson Becker",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 13,
      "name": "Virgil van Dijk",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 14,
      "name": "Jérémy Jacquet",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 15,
      "name": "Milos Kerkez",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 16,
      "name": "Ronald Araújo",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 17,
      "name": "Florian Wirtz",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 18,
      "name": "Alexis Mac Allister",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 19,
      "name": "Dominik Szoboszlai",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 20,
      "name": "Alexander Isak",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 21,
      "name": "Rio Ngumoha",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 22,
      "name": "Bradley Barcola",
      "team": "Liverpool",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
      "delta": 19.7,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 23,
      "name": "Álvaro Valles",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 24,
      "name": "Natan",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 25,
      "name": "Marc Bartra",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 26,
      "name": "Junior Firpo",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 27,
      "name": "Héctor Bellerín",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 28,
      "name": "Isco",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 29,
      "name": "Pablo Fornals",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    },
    {
      "rank": 30,
      "name": "Facundo Bernal",
      "team": "Betis",
      "teamLogo": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
      "delta": 13.8,
      "minutes": 90,
      "matches": 1
    }
  ],
  "PLAYER_BOTTOM": [
    {
      "name": "Anis Hadj Moussa",
      "team": "Feyenoord",
      "delta": -23.2,
      "minutes": 90
    },
    {
      "name": "Javi López",
      "team": "Feyenoord",
      "delta": -23.2,
      "minutes": 90
    },
    {
      "name": "Nacho Ferri",
      "team": "Feyenoord",
      "delta": -23.2,
      "minutes": 90
    },
    {
      "name": "Gjivai Zechiël",
      "team": "Feyenoord",
      "delta": -23.2,
      "minutes": 90
    },
    {
      "name": "Charles Vanhoutte",
      "team": "Feyenoord",
      "delta": -23.2,
      "minutes": 90
    }
  ],
  "IMPORTANCE": 8.6
};
