// Auto-generated Glory log — hechos de gloria e informes de cierre.
window.GLORY_DATA = {
  "UPDATED": "2026-07-23 15:36 UTC",
  "EVENTS": [
    {
      "id": "indycar:win:Grand Prix of Nashville:Álex Palou",
      "sport": "indycar",
      "detail": "IndyCar",
      "text": "Álex Palou ganó en Grand Prix of Nashville",
      "weight": 100,
      "firstSeen": "2026-07-21"
    },
    {
      "id": "f1:win:Moët & Chandon Belgian Grand Prix:Max Verstappen",
      "sport": "f1",
      "detail": "F1",
      "text": "Max Verstappen ganó el Moët & Chandon Belgian Grand Prix",
      "weight": 100,
      "firstSeen": "2026-07-18"
    },
    {
      "id": "nascar:win:NASCAR Cup Series at Atlanta:Ryan Blaney",
      "sport": "nascar",
      "detail": "NASCAR",
      "text": "Ryan Blaney ganó en Echopark Speedway",
      "weight": 100,
      "firstSeen": "2026-07-13"
    },
    {
      "id": "motogp:win:German motorcycle Grand Prix:Marc Márquez",
      "sport": "motogp",
      "detail": "MotoGP",
      "text": "Marc Márquez ganó el German motorcycle Grand Prix",
      "weight": 100,
      "firstSeen": "2026-07-12"
    },
    {
      "id": "motogp:win:Czech Republic motorcycle Grand Prix:Ai Ogura",
      "sport": "motogp",
      "detail": "MotoGP",
      "text": "Ai Ogura ganó el Czech Republic motorcycle Grand Prix",
      "weight": 100,
      "firstSeen": "2026-07-10"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:new1:Brazil (1994-2002)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Brazil (1994-2002) es nuevo nº1 · dinastías",
      "weight": 92,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:TEAMS:new1:Spain",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-ranking-elo",
      "text": "Spain es nuevo nº1 · Ranking Elo",
      "weight": 92,
      "firstSeen": "2026-07-19"
    },
    {
      "id": "rank:mlb:ROAD_TO_GLORY.players:new1:Shohei Ohtani",
      "sport": "mlb",
      "detail": "MLB",
      "anchor": "mlb-road-to-glory",
      "text": "Shohei Ohtani es nuevo nº1 · Road to Glory",
      "weight": 92,
      "firstSeen": "2026-07-10"
    },
    {
      "id": "tennis:in:WTA:Linda Noskova:20260709",
      "sport": "tennis",
      "detail": "Tenis",
      "text": "Linda Noskova entra en el top 10 WTA",
      "weight": 90,
      "anchor": "tennis-wta",
      "firstSeen": "2026-07-13"
    },
    {
      "id": "rank:athletics:allTime:200m_w:in:Julien Alfred",
      "sport": "athletics",
      "detail": "Atletismo",
      "anchor": "athletics-records",
      "text": "Julien Alfred entra en el top-10 histórico · 200m — M",
      "weight": 90,
      "firstSeen": "2026-07-10"
    },
    {
      "id": "rank:athletics:allTime:400m_m:in:Busang Collen Kebinatshipi",
      "sport": "athletics",
      "detail": "Atletismo",
      "anchor": "athletics-records",
      "text": "Busang Collen Kebinatshipi entra en el top-10 histórico · 400m — H",
      "weight": 90,
      "firstSeen": "2026-07-10"
    },
    {
      "id": "cycling:stage:Tour de France:18:Richard Carapaz",
      "sport": "cycling",
      "detail": "Ciclismo",
      "text": "Richard Carapaz ganó la última etapa del Tour de France",
      "weight": 88,
      "firstSeen": "2026-07-23"
    },
    {
      "id": "cycling:stage:Tour de France:17:Jasper Philipsen",
      "sport": "cycling",
      "detail": "Ciclismo",
      "text": "Jasper Philipsen ganó la última etapa del Tour de France",
      "weight": 88,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "cycling:stage:Tour de France:16:Remco Evenepoel",
      "sport": "cycling",
      "detail": "Ciclismo",
      "text": "Remco Evenepoel ganó la última etapa del Tour de France",
      "weight": 88,
      "firstSeen": "2026-07-21"
    },
    {
      "id": "cycling:stage:Tour de France:15:Remco Evenepoel",
      "sport": "cycling",
      "detail": "Ciclismo",
      "text": "Remco Evenepoel ganó la última etapa del Tour de France",
      "weight": 88,
      "firstSeen": "2026-07-20"
    },
    {
      "id": "rank:mlb:ROAD_TO_GLORY.players:in:Willson Contreras",
      "sport": "mlb",
      "detail": "MLB",
      "anchor": "mlb-road-to-glory",
      "text": "Willson Contreras entra en el top-10 · Road to Glory",
      "weight": 84,
      "firstSeen": "2026-07-23"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:in:Uruguay (1924-1930)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Uruguay (1924-1930) entra en el top-10 · dinastías",
      "weight": 84,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:in:Brazil (1958-1962)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Brazil (1958-1962) entra en el top-10 · dinastías",
      "weight": 84,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:in:Spain (2023-present)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Spain (2023-present) entra en el top-10 · dinastías",
      "weight": 84,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:in:Germany (2014-2017)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Germany (2014-2017) entra en el top-10 · dinastías",
      "weight": 84,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:indycar:DRIVERS:in:Rinus VeeKay",
      "sport": "indycar",
      "detail": "IndyCar",
      "anchor": "indycar-campeonato",
      "text": "Rinus VeeKay entra en el top-10 · campeonato",
      "weight": 84,
      "firstSeen": "2026-07-21"
    },
    {
      "id": "rank:mlb:ROAD_TO_GLORY.youngProspects:in:Chase Burns",
      "sport": "mlb",
      "detail": "MLB",
      "anchor": "mlb-jovenes-promesas",
      "text": "Chase Burns entra en el top-10 · jóvenes promesas",
      "weight": 84,
      "firstSeen": "2026-07-21"
    },
    {
      "id": "rank:mlb:ROAD_TO_GLORY.players:in:Chris Sale",
      "sport": "mlb",
      "detail": "MLB",
      "anchor": "mlb-road-to-glory",
      "text": "Chris Sale entra en el top-10 · Road to Glory",
      "weight": 84,
      "firstSeen": "2026-07-18"
    },
    {
      "id": "rank:golf:CURRENT:in:Tommy Fleetwood",
      "sport": "golf",
      "detail": "Golf",
      "anchor": "golf-nivel-actual",
      "text": "Tommy Fleetwood entra en el top-10 · Nivel actual",
      "weight": 84,
      "firstSeen": "2026-07-13"
    },
    {
      "id": "rank:motogp:RIDERS:in:Luca Marini",
      "sport": "motogp",
      "detail": "MotoGP",
      "anchor": "motogp-mundial",
      "text": "Luca Marini entra en el top-10 · Mundial",
      "weight": 84,
      "firstSeen": "2026-07-12"
    },
    {
      "id": "rank:afl:LADDER:in:St Kilda",
      "sport": "afl",
      "detail": "AFL",
      "anchor": "afl-clasificacion",
      "text": "St Kilda entra en el top-10 · clasificación",
      "weight": 84,
      "firstSeen": "2026-07-11"
    },
    {
      "id": "tennis:out:WTA:Victoria Mboko:20260709",
      "sport": "tennis",
      "detail": "Tenis",
      "text": "Victoria Mboko sale del top 10 WTA",
      "weight": 78,
      "anchor": "tennis-wta",
      "firstSeen": "2026-07-13"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:out:Brazil (1958-1970)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Brazil (1958-1970) cae del top-10 · dinastías",
      "weight": 74,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:out:Uruguay (1928-1950)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Uruguay (1928-1950) cae del top-10 · dinastías",
      "weight": 74,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:out:Argentina (1978-1986)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Argentina (1978-1986) cae del top-10 · dinastías",
      "weight": 74,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:football:ROAD_TO_GLORY.dynasties:era:out:Germany (1980-1990)",
      "sport": "football",
      "detail": "Fútbol",
      "anchor": "football-dinastias",
      "text": "Germany (1980-1990) cae del top-10 · dinastías",
      "weight": 74,
      "firstSeen": "2026-07-22"
    },
    {
      "id": "rank:indycar:DRIVERS:out:Scott Dixon",
      "sport": "indycar",
      "detail": "IndyCar",
      "anchor": "indycar-campeonato",
      "text": "Scott Dixon cae del top-10 · campeonato",
      "weight": 74,
      "firstSeen": "2026-07-21"
    },
    {
      "id": "rank:motogp:RIDERS:out:Fermín Aldeguer",
      "sport": "motogp",
      "detail": "MotoGP",
      "anchor": "motogp-mundial",
      "text": "Fermín Aldeguer cae del top-10 · Mundial",
      "weight": 74,
      "firstSeen": "2026-07-12"
    }
  ],
  "REPORTS": [],
  "REPORT_SEEN": [
    {
      "id": "nhl:champ:CAR:2025-26",
      "firstSeen": "2026-07-10"
    },
    {
      "id": "nba:champ:NY:2025-26",
      "firstSeen": "2026-07-06"
    }
  ],
  "SNAPSHOTS": {
    "nhl:ROAD_TO_GLORY.players": [
      "Nikita Kucherov",
      "Nathan MacKinnon",
      "Connor McDavid",
      "Evgeni Malkin",
      "Leon Draisaitl",
      "Artemi Panarin",
      "David Pastrnak",
      "Mikko Rantanen",
      "Mark Stone",
      "Jake Guentzel"
    ],
    "nhl:ROAD_TO_GLORY.teams": [
      "Vegas Golden Knights",
      "Colorado Avalanche",
      "Florida Panthers",
      "St. Louis Blues",
      "Carolina Hurricanes",
      "Dallas Stars",
      "Minnesota Wild",
      "Boston Bruins",
      "Edmonton Oilers",
      "New York Rangers"
    ],
    "nhl:ROAD_TO_GLORY.youngProspects": [
      "Oliver Bonk",
      "Macklin Celebrini",
      "Porter Martone",
      "Connor Bedard",
      "Jack Hughes",
      "Matt Boldy",
      "Ilya Protas",
      "Lane Hutson",
      "Leo Carlsson",
      "Cole Caufield"
    ],
    "nba:ROAD_TO_GLORY.players": [
      "LeBron James",
      "Nikola Jokic",
      "Kevin Durant",
      "Shai Gilgeous-Alexander",
      "Jayson Tatum",
      "Jaylen Brown",
      "Joel Embiid",
      "Jalen Brunson",
      "Dillon Brooks",
      "James Harden"
    ],
    "nba:ROAD_TO_GLORY.teams": [
      "Oklahoma City Thunder",
      "Boston Celtics",
      "Denver Nuggets",
      "Los Angeles Lakers",
      "San Antonio Spurs",
      "New York Knicks",
      "Golden State Warriors",
      "Minnesota Timberwolves",
      "Milwaukee Bucks",
      "Indiana Pacers"
    ],
    "nba:ROAD_TO_GLORY.youngProspects": [
      "Paolo Banchero",
      "Victor Wembanyama",
      "Cade Cunningham",
      "Scottie Barnes",
      "Alperen Sengun",
      "Tyrese Maxey",
      "Amen Thompson",
      "Stephon Castle",
      "Deni Avdija",
      "VJ Edgecombe"
    ],
    "mlb:ROAD_TO_GLORY.players": [
      "Shohei Ohtani",
      "Mike Trout",
      "Freddie Freeman",
      "Bryce Harper",
      "Juan Soto",
      "Yordan Alvarez",
      "Kyle Schwarber",
      "Jacob Misiorowski",
      "Chris Sale",
      "Willson Contreras"
    ],
    "mlb:ROAD_TO_GLORY.teams": [
      "Los Angeles Dodgers",
      "Houston Astros",
      "Atlanta Braves",
      "Texas Rangers",
      "New York Yankees",
      "Philadelphia Phillies",
      "Seattle Mariners",
      "Baltimore Orioles",
      "San Diego Padres",
      "New York Mets"
    ],
    "mlb:ROAD_TO_GLORY.youngProspects": [
      "Jacob Misiorowski",
      "James Wood",
      "Sal Stewart",
      "Jordan Walker",
      "CJ Abrams",
      "Junior Caminero",
      "Pete Crow-Armstrong",
      "Chase Burns",
      "Nick Kurtz",
      "Cam Schlittler"
    ],
    "nfl:ROAD_TO_GLORY.players": [
      "Matthew Stafford",
      "Jared Goff",
      "Dak Prescott",
      "Jacoby Brissett",
      "Baker Mayfield",
      "Jalen Hurts",
      "Josh Allen",
      "Drake Maye",
      "Sam Darnold",
      "Trevor Lawrence"
    ],
    "nfl:ROAD_TO_GLORY.youngProspects": [
      "Drake Maye",
      "Caleb Williams",
      "Bryce Young",
      "C.J. Stroud",
      "Cam Ward",
      "Jaxson Dart"
    ],
    "tennis:ATP": [
      "Jannik Sinner",
      "Carlos Alcaraz",
      "Alexander Zverev",
      "Novak Djokovic",
      "Arthur Fils",
      "Casper Ruud",
      "Lorenzo Musetti",
      "Tommy Paul",
      "Daniil Medvedev",
      "Felix Auger Aliassime"
    ],
    "tennis:WTA": [
      "Aryna Sabalenka",
      "Elena Rybakina",
      "Mirra Andreeva",
      "Coco Gauff",
      "Iga Swiatek",
      "Marta Kostyuk",
      "Jessica Pegula",
      "Elina Svitolina",
      "Karolina Muchova",
      "Amanda Anisimova"
    ],
    "tennis:ATP_LEGENDS": [
      "Novak Djokovic",
      "Rafael Nadal",
      "Roger Federer",
      "Pete Sampras",
      "Björn Borg",
      "Ivan Lendl",
      "Jimmy Connors",
      "John McEnroe",
      "Andre Agassi",
      "Mats Wilander"
    ],
    "tennis:WTA_LEGENDS": [
      "Steffi Graf",
      "Serena Williams",
      "Martina Navratilova",
      "Chris Evert",
      "Billie Jean King",
      "Monica Seles",
      "Justine Henin",
      "Iga Swiatek",
      "Venus Williams",
      "Martina Hingis"
    ],
    "cycling:LEGENDS": [
      "Eddy Merckx",
      "Bernard Hinault",
      "Fausto Coppi",
      "Jacques Anquetil",
      "Tadej Pogacar",
      "Miguel Indurain",
      "Chris Froome",
      "Felice Gimondi",
      "Alberto Contador",
      "Laurent Fignon"
    ],
    "cycling:CURRENT_RIDERS": [
      "Tadej Pogacar",
      "Primoz Roglic",
      "Jonas Vingegaard",
      "Mathieu van der Poel",
      "Remco Evenepoel",
      "Egan Bernal",
      "Julian Alaphilippe",
      "Richard Carapaz",
      "Jai Hindley",
      "Wout van Aert"
    ],
    "cycling:CURRENT_PROSPECTS": [
      "Isaac del Toro",
      "Paul Seixas"
    ],
    "sumo:BANZUKE": [
      "Hoshoryu",
      "Onosato",
      "Kirishima",
      "Kotozakura",
      "Atamifuji",
      "Kotoshoho",
      "Wakatakakage",
      "Aonishiki",
      "Yoshinofuji",
      "Oho"
    ],
    "nascar:DRIVERS": [
      "Tyler Reddick",
      "Denny Hamlin",
      "Ryan Blaney",
      "Chase Elliott",
      "Shane van Gisbergen",
      "Ty Gibbs",
      "Carson Hocevar",
      "Chase Briscoe",
      "Daniel Suarez",
      "Kyle Larson"
    ],
    "nascar:LEGENDS": [
      "Richard Petty",
      "Jimmie Johnson",
      "Dale Earnhardt",
      "Jeff Gordon",
      "David Pearson",
      "Cale Yarborough",
      "Darrell Waltrip",
      "Joey Logano",
      "Kyle Busch",
      "Kyle Larson"
    ],
    "motogp:RIDERS": [
      "Jorge Martín",
      "Ai Ogura",
      "Marc Márquez",
      "Marco Bezzecchi",
      "Fabio Di Giannantonio",
      "Raúl Fernández",
      "Pedro Acosta",
      "Francesco Bagnaia",
      "Álex Márquez",
      "Luca Marini"
    ],
    "motogp:LEGENDS": [
      "Giacomo Agostini",
      "Valentino Rossi",
      "Marc Márquez",
      "Mick Doohan",
      "Eddie Lawson",
      "Jorge Lorenzo",
      "Kenny Roberts",
      "Wayne Rainey",
      "Casey Stoner",
      "Francesco Bagnaia"
    ],
    "f1:DRIVERS": [
      "Kimi Antonelli",
      "Lewis Hamilton",
      "George Russell",
      "Charles Leclerc",
      "Lando Norris",
      "Oscar Piastri",
      "Max Verstappen",
      "Isack Hadjar",
      "Pierre Gasly",
      "Liam Lawson"
    ],
    "f1:LEGENDS": [
      "Lewis Hamilton",
      "Michael Schumacher",
      "Sebastian Vettel",
      "Max Verstappen",
      "Alain Prost",
      "Juan Manuel Fangio",
      "Ayrton Senna",
      "Niki Lauda",
      "Nelson Piquet",
      "Jackie Stewart"
    ],
    "indycar:DRIVERS": [
      "Álex Palou",
      "David Malukas",
      "Kyle Kirkwood",
      "Christian Lundgaard",
      "Pato O'Ward",
      "Josef Newgarden",
      "Felix Rosenqvist",
      "Scott McLaughlin",
      "Marcus Ericsson",
      "Rinus VeeKay"
    ],
    "indycar:LEGENDS": [
      "A. J. Foyt",
      "Scott Dixon",
      "Mario Andretti",
      "Dario Franchitti",
      "Al Unser",
      "Will Power",
      "Alex Palou",
      "Bobby Unser",
      "Josef Newgarden",
      "Helio Castroneves"
    ],
    "golf:CURRENT": [
      "Scottie Scheffler",
      "Matt Fitzpatrick",
      "Cameron Young",
      "Wyndham Clark",
      "Chris Gotterup",
      "Collin Morikawa",
      "Si Woo Kim",
      "Sam Burns",
      "Tommy Fleetwood",
      "Ludvig Åberg"
    ],
    "golf:LEGENDS": [
      "Tiger Woods",
      "Jack Nicklaus",
      "Walter Hagen",
      "Ben Hogan",
      "Sam Snead",
      "Gary Player",
      "Tom Watson",
      "Arnold Palmer",
      "Harry Vardon",
      "Gene Sarazen"
    ],
    "afl:LADDER": [
      "Fremantle",
      "Sydney",
      "Hawthorn",
      "Brisbane Lions",
      "Adelaide",
      "Melbourne",
      "Collingwood",
      "Western Bulldogs",
      "Geelong",
      "St Kilda"
    ],
    "cricket:ROAD_TO_GLORY.players": [
      "JJ Bumrah",
      "MA Starc",
      "MJ Henry",
      "KA Maharaj",
      "RA Jadeja",
      "Taijul Islam",
      "JNT Seales",
      "Mehedi Hasan Miraz",
      "Nauman Ali",
      "AAP Atkinson"
    ],
    "athletics:allTime:100m_m": [
      "Usain Bolt",
      "Usain Bolt",
      "Usain Bolt",
      "Tyson Gay",
      "Tyson Gay",
      "Usain Bolt",
      "Asafa Powell",
      "Asafa Powell",
      "Justin Gatlin",
      "Yohan Blake"
    ],
    "athletics:allTime:100m_w": [
      "Florence Griffith Joyner",
      "Elaine Thompson-Herah",
      "Shelly-Ann Fraser-Pryce",
      "Florence Griffith Joyner",
      "Melissa Jefferson-Wooden",
      "Florence Griffith Joyner",
      "Shelly-Ann Fraser-Pryce",
      "Adaejah Hodge",
      "Carmelita Jeter",
      "Elaine Thompson-Herah"
    ],
    "athletics:allTime:200m_m": [
      "Usain Bolt",
      "Yohan Blake",
      "Usain Bolt",
      "Noah Lyles",
      "Michael Johnson",
      "Usain Bolt",
      "Usain Bolt",
      "Yohan Blake",
      "Noah Lyles",
      "Letsile Tebogo"
    ],
    "athletics:allTime:200m_w": [
      "Florence Griffith Joyner",
      "Shericka Jackson",
      "Shericka Jackson",
      "Shericka Jackson",
      "Julien Alfred",
      "Elaine Thompson-Herah",
      "Shericka Jackson",
      "Griffith Joyner",
      "Shericka Jackson",
      "Gabby Thomas"
    ],
    "athletics:allTime:400m_m": [
      "Wayde van Niekerk",
      "Michael Johnson",
      "Butch Reynolds",
      "Samuel Ogazi",
      "Michael Johnson",
      "Quincy Hall",
      "Michael Johnson",
      "Matthew Hudson-Smith",
      "Busang Collen Kebinatshipi",
      "Jeremy Wariner"
    ],
    "athletics:allTime:400m_w": [
      "Marita Koch",
      "Sydney McLaughlin-Levrone",
      "Marileidy Paulino",
      "Jarmila Kratochvílová",
      "Salwa Eid Naser",
      "Marita Koch",
      "Marileidy Paulino",
      "Salwa Eid Naser",
      "Marita Koch",
      "Marie-José Pérec"
    ],
    "athletics:allTime:110mh_m": [
      "Ja'Kobe Tharp",
      "Ja&#39;Kobe Tharp",
      "Aries Merritt",
      "Grant Holloway",
      "Devon Allen",
      "Grant Holloway",
      "Jamal Britt",
      "Dayron Robles",
      "Cordell Tinch",
      "Liu Xiang"
    ],
    "athletics:allTime:100mh_w": [
      "Tobi Amusan",
      "Masai Russell",
      "Masai Russell",
      "Tia Jones",
      "Masai Russell",
      "Kendra Harrison",
      "Yordanka Donkova",
      "Masai Russell",
      "Yordanka Donkova",
      "Ackera Nugent"
    ],
    "athletics:allTime:400mh_m": [
      "Karsten Warholm",
      "Rai Benjamin",
      "Karsten Warholm",
      "Alison dos Santos",
      "Rai Benjamin",
      "Rai Benjamin",
      "Karsten Warholm",
      "Karsten Warholm",
      "Karsten Warholm",
      "Rai Benjamin"
    ],
    "athletics:allTime:400mh_w": [
      "Sydney McLaughlin-Levrone",
      "Sydney McLaughlin-Levrone",
      "Sydney McLaughlin-Levrone",
      "Femke Bol",
      "Femke Bol",
      "Sydney McLaughlin-Levrone",
      "Femke Bol",
      "Sydney McLaughlin-Levrone",
      "Femke Bol",
      "Dalilah Muhammad"
    ],
    "athletics:allTime:800m_m": [
      "David Rudisha",
      "David Rudisha",
      "David Rudisha",
      "Wilson Kipketer",
      "Emmanuel Wanyonyi",
      "Marco Arop",
      "Wilson Kipketer",
      "David Rudisha",
      "Emmanuel Wanyonyi",
      "Djamel Sedjati"
    ],
    "athletics:allTime:800m_w": [
      "Jarmila Kratochvílová",
      "Nadezhda Olizarenko",
      "Audrey Werro",
      "Audrey Werro",
      "Pamela Jelimo",
      "Caster Semenya",
      "Keely Hodgkinson",
      "Ana Fidelia Quirot",
      "Audrey Werro",
      "Caster Semenya"
    ],
    "athletics:allTime:1500m_m": [
      "Hicham El Guerrouj",
      "El Guerrouj",
      "Bernard Lagat",
      "El Guerrouj",
      "Asbel Kiprop",
      "Jakob Ingebrigtsen",
      "El Guerrouj",
      "El Guerrouj",
      "Jakob Ingebrigtsen",
      "El Guerrouj"
    ],
    "athletics:allTime:1500m_w": [
      "Faith Kipyegon",
      "Faith Kipyegon",
      "Faith Kipyegon",
      "Genzebe Dibaba",
      "Gudaf Tsegay",
      "Faith Kipyegon",
      "Qu Yunxia",
      "Gudaf Tsegay",
      "Faith Kipyegon",
      "Jessica Hull"
    ],
    "athletics:allTime:5000m_m": [
      "Joshua Cheptegei",
      "Hagos Gebrhiwet",
      "Kenenisa Bekele",
      "Yomif Kejelcha",
      "Haile Gebrselassie",
      "Daniel Komen",
      "K. Bekele",
      "Berihu Aregawi",
      "Jacob Kiplimo",
      "Joshua Cheptegei"
    ],
    "athletics:allTime:5000m_w": [
      "Beatrice Chebet",
      "Gudaf Tsegay",
      "Agnes Jebet Ngetich",
      "Beatrice Chebet",
      "Gudaf Tsegay",
      "Faith Kipyegon",
      "Beatrice Chebet",
      "Letesenbet Gidey",
      "Letesenbet Gidey",
      "Letesenbet Gidey"
    ],
    "athletics:allTime:3000msc_m": [
      "Lamecha Girma",
      "Saif Saaeed Shaheen",
      "Brimin Kipruto",
      "Paul Kipsiele Koech",
      "Brahim Boulami",
      "Saif Saaeed Shaheen",
      "Bernard Barmasai",
      "Ezekiel Kemboi",
      "Moses Kiptanui",
      "Saif Saaeed Shaheen"
    ],
    "athletics:allTime:3000msc_w": [
      "Beatrice Chepkoech",
      "Winfred Yavi",
      "Winfred Yavi",
      "Peruth Chemutai",
      "Faith Cherotich",
      "Winfred Yavi",
      "Winfred Yavi",
      "Peruth Chemutai",
      "Peruth Chemutai",
      "Faith Cherotich"
    ],
    "athletics:allTime:hj_m": [
      "Javier Sotomayor",
      "Javier Sotomayor",
      "Javier Sotomayor",
      "Mutaz Essa Barshim",
      "Patrik Sjöberg",
      "Javier Sotomayor",
      "Bohdan Bondarenko",
      "Mutaz Essa Barshim",
      "Igor Paklin",
      "Javier Sotomayor"
    ],
    "athletics:allTime:hj_w": [
      "Yaroslava Mahuchikh",
      "Stefka Kostadinova",
      "Stefka Kostadinova",
      "Blanka Vlašić",
      "Lyudmila Andonova",
      "Stefka Kostadinova",
      "Anna Chicherova",
      "Stefka Kostadinova",
      "Kajsa Bergqvist",
      "Blanka Vlašić"
    ],
    "athletics:allTime:pv_m": [
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Armand Duplantis",
      "Emmanouil Karalis"
    ],
    "athletics:allTime:pv_w": [
      "Yelena Isinbayeva",
      "Yelena Isinbayeva",
      "Yelena Isinbayeva",
      "Yelena Isinbayeva",
      "Yelena Isinbayeva",
      "Anzhelika Sidorova",
      "Yelena Isinbayeva",
      "Sandi Morris",
      "Yelena Isinbayeva",
      "Yelena Isinbayeva"
    ],
    "athletics:allTime:lj_m": [
      "Mike Powell",
      "Bob Beamon",
      "Carl Lewis",
      "Robert Emmiyan",
      "Carl Lewis",
      "Carl Lewis",
      "Carl Lewis",
      "Carl Lewis",
      "Larry Myricks",
      "Erick Walder"
    ],
    "athletics:allTime:lj_w": [
      "Galina Chistyakova",
      "Jackie Joyner-Kersee",
      "Jackie Joyner-Kersee",
      "Heike Drechsler",
      "Heike Drechsler",
      "Heike Drechsler",
      "Heike Drechsler",
      "Anişoara Cuşmir",
      "Tatyana Kotova",
      "Heike Drechsler"
    ],
    "athletics:allTime:tj_m": [
      "Jonathan Edwards",
      "Christian Taylor",
      "Jordan Díaz",
      "Jonathan Edwards",
      "Will Claye",
      "Christian Taylor",
      "Kenny Harrison",
      "Pedro Pichardo",
      "Pedro Pichardo",
      "Teddy Tamgho"
    ],
    "athletics:allTime:tj_w": [
      "Yulimar Rojas",
      "Yulimar Rojas",
      "Inessa Kravets",
      "Yulimar Rojas",
      "Yulimar Rojas",
      "Yulimar Rojas",
      "Yulimar Rojas",
      "Françoise Mbango Etone",
      "Yulimar Rojas",
      "Yulimar Rojas"
    ],
    "athletics:allTime:sp_m": [
      "Ryan Crouser",
      "Ryan Crouser",
      "Ryan Crouser",
      "Ryan Crouser",
      "Joe Kovacs",
      "Ryan Crouser",
      "Joe Kovacs",
      "Randy Barnes",
      "Ryan Crouser",
      "Randy Barnes"
    ],
    "athletics:allTime:sp_w": [
      "Natalya Lisovskaya",
      "Natalya Lisovskaya",
      "Natalya Lisovskaya",
      "Natalya Lisovskaya",
      "Ilona Slupianek",
      "Ilona Slupianek",
      "Ilona Slupianek",
      "Ilona Slupianek",
      "Ilona Slupianek",
      "Ilona Slupianek"
    ],
    "athletics:allTime:dt_m": [
      "Mykolas Alekna",
      "M. Alekna",
      "Matthew Denny",
      "M. Alekna",
      "Matthew Denny",
      "Jürgen Schult",
      "Matthew Denny",
      "Steven Richter",
      "Virgilijus Alekna",
      "Matthew Denny"
    ],
    "athletics:allTime:dt_w": [
      "Gabriele Reinsch",
      "Zdeňka Šilhavá",
      "Gabriele Reinsch",
      "Ilke Wyludda",
      "Diana Gansky",
      "Diana Gansky",
      "Daniela Costian",
      "Daniela Costian",
      "Valarie Allman",
      "Gabriele Reinsch"
    ],
    "athletics:allTime:jt_m": [
      "Jan Železný",
      "Johannes Vetter",
      "Johannes Vetter",
      "Jan Železný",
      "Jan Železný",
      "Jan Železný",
      "Johannes Vetter",
      "Johannes Vetter",
      "Jan Železný",
      "Thomas Röhler"
    ],
    "athletics:allTime:jt_w": [
      "Barbora Špotáková",
      "Yan Ziyi",
      "Ziyi Yan",
      "Osleidys Menéndez",
      "Barbora Špotáková",
      "Osleidys Menéndez",
      "Osleidys Menéndez",
      "Barbora Špotáková",
      "Maria Andrejczyk",
      "Mariya Abakumova"
    ],
    "rugby:ROAD_TO_GLORY.dynasties:era": [
      "New Zealand (2004-2019)",
      "New Zealand (1987-1992)",
      "New Zealand (1963-1971)",
      "Australia (1999-2002)",
      "New Zealand (1981-1986)",
      "South Africa (1949-1957)",
      "South Africa (1928-1949)",
      "New Zealand (1995-1998)",
      "Wales (1902-1906)",
      "Scotland (1896-1900)"
    ],
    "football:ROAD_TO_GLORY.dynasties:era": [
      "Brazil (1994-2002)",
      "Uruguay (1924-1930)",
      "Brazil (1958-1962)",
      "Italy (1934-1938)",
      "Spain (2008-2012)",
      "Argentina (2021-present)",
      "Germany (1972-1976)",
      "Spain (2023-present)",
      "France (1998-2001)",
      "Germany (2014-2017)"
    ],
    "football:TEAMS": [
      "Spain",
      "Argentina",
      "England",
      "France",
      "Netherlands",
      "Portugal",
      "Brazil",
      "Italy",
      "Germany",
      "Uruguay"
    ]
  }
};
