// NFL Tracker - generated from ESPN public API data.
// Run `python3 scripts/update_nfl_data.py` to refresh.
window.NFL_DATA = {
  "TEAMS": [
    {
      "code": "SEA",
      "city": "Seattle Seahawks",
      "shortName": "Seattle",
      "commonName": "Seahawks",
      "conf": "NFC",
      "div": "NFC West",
      "gp": 17,
      "w": 14,
      "l": 3,
      "t": 0,
      "winPct": 0.824,
      "pf": 483,
      "pa": 292,
      "pd": 191,
      "seed": 1,
      "score": 75,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
      "colors": {
        "primary": "#002244",
        "secondary": "#69be28"
      }
    },
    {
      "code": "NE",
      "city": "New England Patriots",
      "shortName": "New England",
      "commonName": "Patriots",
      "conf": "AFC",
      "div": "AFC East",
      "gp": 17,
      "w": 14,
      "l": 3,
      "t": 0,
      "winPct": 0.824,
      "pf": 490,
      "pa": 320,
      "pd": 170,
      "seed": 2,
      "score": 74,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
      "colors": {
        "primary": "#002244",
        "secondary": "#c60c30"
      }
    },
    {
      "code": "DEN",
      "city": "Denver Broncos",
      "shortName": "Denver",
      "commonName": "Broncos",
      "conf": "AFC",
      "div": "AFC West",
      "gp": 17,
      "w": 14,
      "l": 3,
      "t": 0,
      "winPct": 0.824,
      "pf": 401,
      "pa": 311,
      "pd": 90,
      "seed": 1,
      "score": 70,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
      "colors": {
        "primary": "#fb4f14",
        "secondary": "#002244"
      }
    },
    {
      "code": "JAX",
      "city": "Jacksonville Jaguars",
      "shortName": "Jacksonville",
      "commonName": "Jaguars",
      "conf": "AFC",
      "div": "AFC South",
      "gp": 17,
      "w": 13,
      "l": 4,
      "t": 0,
      "winPct": 0.765,
      "pf": 474,
      "pa": 336,
      "pd": 138,
      "seed": 3,
      "score": 68,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
      "colors": {
        "primary": "#006778",
        "secondary": "#9f792c"
      }
    },
    {
      "code": "LAR",
      "city": "Los Angeles Rams",
      "shortName": "Los Angeles",
      "commonName": "Rams",
      "conf": "NFC",
      "div": "NFC West",
      "gp": 17,
      "w": 12,
      "l": 5,
      "t": 0,
      "winPct": 0.706,
      "pf": 518,
      "pa": 346,
      "pd": 172,
      "seed": 5,
      "score": 65,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
      "colors": {
        "primary": "#003594",
        "secondary": "#ffd100"
      }
    },
    {
      "code": "BUF",
      "city": "Buffalo Bills",
      "shortName": "Buffalo",
      "commonName": "Bills",
      "conf": "AFC",
      "div": "AFC East",
      "gp": 17,
      "w": 12,
      "l": 5,
      "t": 0,
      "winPct": 0.706,
      "pf": 481,
      "pa": 365,
      "pd": 116,
      "seed": 6,
      "score": 62,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
      "colors": {
        "primary": "#00338d",
        "secondary": "#c60c30"
      }
    },
    {
      "code": "HOU",
      "city": "Houston Texans",
      "shortName": "Houston",
      "commonName": "Texans",
      "conf": "AFC",
      "div": "AFC South",
      "gp": 17,
      "w": 12,
      "l": 5,
      "t": 0,
      "winPct": 0.706,
      "pf": 404,
      "pa": 295,
      "pd": 109,
      "seed": 5,
      "score": 62,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
      "colors": {
        "primary": "#03202f",
        "secondary": "#a71930"
      }
    },
    {
      "code": "SF",
      "city": "San Francisco 49ers",
      "shortName": "San Francisco",
      "commonName": "49ers",
      "conf": "NFC",
      "div": "NFC West",
      "gp": 17,
      "w": 12,
      "l": 5,
      "t": 0,
      "winPct": 0.706,
      "pf": 437,
      "pa": 371,
      "pd": 66,
      "seed": 6,
      "score": 60,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
      "colors": {
        "primary": "#aa0000",
        "secondary": "#b3995d"
      }
    },
    {
      "code": "PHI",
      "city": "Philadelphia Eagles",
      "shortName": "Philadelphia",
      "commonName": "Eagles",
      "conf": "NFC",
      "div": "NFC East",
      "gp": 17,
      "w": 11,
      "l": 6,
      "t": 0,
      "winPct": 0.647,
      "pf": 379,
      "pa": 325,
      "pd": 54,
      "seed": 3,
      "score": 54,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
      "colors": {
        "primary": "#004c54",
        "secondary": "#a5acaf"
      }
    },
    {
      "code": "LAC",
      "city": "Los Angeles Chargers",
      "shortName": "Los Angeles",
      "commonName": "Chargers",
      "conf": "AFC",
      "div": "AFC West",
      "gp": 17,
      "w": 11,
      "l": 6,
      "t": 0,
      "winPct": 0.647,
      "pf": 368,
      "pa": 340,
      "pd": 28,
      "seed": 7,
      "score": 53,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
      "colors": {
        "primary": "#0080c6",
        "secondary": "#ffb612"
      }
    },
    {
      "code": "CHI",
      "city": "Chicago Bears",
      "shortName": "Chicago",
      "commonName": "Bears",
      "conf": "NFC",
      "div": "NFC North",
      "gp": 17,
      "w": 11,
      "l": 6,
      "t": 0,
      "winPct": 0.647,
      "pf": 441,
      "pa": 415,
      "pd": 26,
      "seed": 2,
      "score": 53,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
      "colors": {
        "primary": "#0b162a",
        "secondary": "#c83803"
      }
    },
    {
      "code": "PIT",
      "city": "Pittsburgh Steelers",
      "shortName": "Pittsburgh",
      "commonName": "Steelers",
      "conf": "AFC",
      "div": "AFC North",
      "gp": 17,
      "w": 10,
      "l": 7,
      "t": 0,
      "winPct": 0.588,
      "pf": 397,
      "pa": 387,
      "pd": 10,
      "seed": 4,
      "score": 48,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
      "colors": {
        "primary": "#101820",
        "secondary": "#ffb612"
      }
    },
    {
      "code": "DET",
      "city": "Detroit Lions",
      "shortName": "Detroit",
      "commonName": "Lions",
      "conf": "NFC",
      "div": "NFC North",
      "gp": 17,
      "w": 9,
      "l": 8,
      "t": 0,
      "winPct": 0.529,
      "pf": 481,
      "pa": 413,
      "pd": 68,
      "seed": 9,
      "score": 46,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
      "colors": {
        "primary": "#0076b6",
        "secondary": "#b0b7bc"
      }
    },
    {
      "code": "GB",
      "city": "Green Bay Packers",
      "shortName": "Green Bay",
      "commonName": "Packers",
      "conf": "NFC",
      "div": "NFC North",
      "gp": 17,
      "w": 9,
      "l": 7,
      "t": 1,
      "winPct": 0.559,
      "pf": 391,
      "pa": 360,
      "pd": 31,
      "seed": 7,
      "score": 46,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
      "colors": {
        "primary": "#203731",
        "secondary": "#ffb612"
      }
    },
    {
      "code": "MIN",
      "city": "Minnesota Vikings",
      "shortName": "Minnesota",
      "commonName": "Vikings",
      "conf": "NFC",
      "div": "NFC North",
      "gp": 17,
      "w": 9,
      "l": 8,
      "t": 0,
      "winPct": 0.529,
      "pf": 344,
      "pa": 333,
      "pd": 11,
      "seed": 8,
      "score": 43,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
      "colors": {
        "primary": "#4f2683",
        "secondary": "#ffc62f"
      }
    },
    {
      "code": "IND",
      "city": "Indianapolis Colts",
      "shortName": "Indianapolis",
      "commonName": "Colts",
      "conf": "AFC",
      "div": "AFC South",
      "gp": 17,
      "w": 8,
      "l": 9,
      "t": 0,
      "winPct": 0.471,
      "pf": 466,
      "pa": 412,
      "pd": 54,
      "seed": 8,
      "score": 40,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
      "colors": {
        "primary": "#002c5f",
        "secondary": "#a2aaad"
      }
    },
    {
      "code": "BAL",
      "city": "Baltimore Ravens",
      "shortName": "Baltimore",
      "commonName": "Ravens",
      "conf": "AFC",
      "div": "AFC North",
      "gp": 17,
      "w": 8,
      "l": 9,
      "t": 0,
      "winPct": 0.471,
      "pf": 424,
      "pa": 398,
      "pd": 26,
      "seed": 9,
      "score": 39,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
      "colors": {
        "primary": "#241773",
        "secondary": "#9e7c0c"
      }
    },
    {
      "code": "TB",
      "city": "Tampa Bay Buccaneers",
      "shortName": "Tampa Bay",
      "commonName": "Buccaneers",
      "conf": "NFC",
      "div": "NFC South",
      "gp": 17,
      "w": 8,
      "l": 9,
      "t": 0,
      "winPct": 0.471,
      "pf": 380,
      "pa": 411,
      "pd": -31,
      "seed": 10,
      "score": 36,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
      "colors": {
        "primary": "#d50a0a",
        "secondary": "#ff7900"
      }
    },
    {
      "code": "ATL",
      "city": "Atlanta Falcons",
      "shortName": "Atlanta",
      "commonName": "Falcons",
      "conf": "NFC",
      "div": "NFC South",
      "gp": 17,
      "w": 8,
      "l": 9,
      "t": 0,
      "winPct": 0.471,
      "pf": 353,
      "pa": 401,
      "pd": -48,
      "seed": 11,
      "score": 35,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
      "colors": {
        "primary": "#a71930",
        "secondary": "#000000"
      }
    },
    {
      "code": "CAR",
      "city": "Carolina Panthers",
      "shortName": "Carolina",
      "commonName": "Panthers",
      "conf": "NFC",
      "div": "NFC South",
      "gp": 17,
      "w": 8,
      "l": 9,
      "t": 0,
      "winPct": 0.471,
      "pf": 311,
      "pa": 380,
      "pd": -69,
      "seed": 4,
      "score": 34,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
      "colors": {
        "primary": "#0085ca",
        "secondary": "#101820"
      }
    },
    {
      "code": "DAL",
      "city": "Dallas Cowboys",
      "shortName": "Dallas",
      "commonName": "Cowboys",
      "conf": "NFC",
      "div": "NFC East",
      "gp": 17,
      "w": 7,
      "l": 9,
      "t": 1,
      "winPct": 0.441,
      "pf": 471,
      "pa": 511,
      "pd": -40,
      "seed": 12,
      "score": 33,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
      "colors": {
        "primary": "#003594",
        "secondary": "#869397"
      }
    },
    {
      "code": "MIA",
      "city": "Miami Dolphins",
      "shortName": "Miami",
      "commonName": "Dolphins",
      "conf": "AFC",
      "div": "AFC East",
      "gp": 17,
      "w": 7,
      "l": 10,
      "t": 0,
      "winPct": 0.412,
      "pf": 347,
      "pa": 424,
      "pd": -77,
      "seed": 10,
      "score": 29,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
      "colors": {
        "primary": "#008e97",
        "secondary": "#fc4c02"
      }
    },
    {
      "code": "KC",
      "city": "Kansas City Chiefs",
      "shortName": "Kansas City",
      "commonName": "Chiefs",
      "conf": "AFC",
      "div": "AFC West",
      "gp": 17,
      "w": 6,
      "l": 11,
      "t": 0,
      "winPct": 0.353,
      "pf": 362,
      "pa": 328,
      "pd": 34,
      "seed": 12,
      "score": 30,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
      "colors": {
        "primary": "#e31837",
        "secondary": "#ffb612"
      }
    },
    {
      "code": "NO",
      "city": "New Orleans Saints",
      "shortName": "New Orleans",
      "commonName": "Saints",
      "conf": "NFC",
      "div": "NFC South",
      "gp": 17,
      "w": 6,
      "l": 11,
      "t": 0,
      "winPct": 0.353,
      "pf": 306,
      "pa": 383,
      "pd": -77,
      "seed": 13,
      "score": 25,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
      "colors": {
        "primary": "#d3bc8d",
        "secondary": "#101820"
      }
    },
    {
      "code": "CIN",
      "city": "Cincinnati Bengals",
      "shortName": "Cincinnati",
      "commonName": "Bengals",
      "conf": "AFC",
      "div": "AFC North",
      "gp": 17,
      "w": 6,
      "l": 11,
      "t": 0,
      "winPct": 0.353,
      "pf": 414,
      "pa": 492,
      "pd": -78,
      "seed": 11,
      "score": 25,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
      "colors": {
        "primary": "#fb4f14",
        "secondary": "#000000"
      }
    },
    {
      "code": "WSH",
      "city": "Washington Commanders",
      "shortName": "Washington",
      "commonName": "Commanders",
      "conf": "NFC",
      "div": "NFC East",
      "gp": 17,
      "w": 5,
      "l": 12,
      "t": 0,
      "winPct": 0.294,
      "pf": 356,
      "pa": 451,
      "pd": -95,
      "seed": 14,
      "score": 19,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
      "colors": {
        "primary": "#5a1414",
        "secondary": "#ffb612"
      }
    },
    {
      "code": "CLE",
      "city": "Cleveland Browns",
      "shortName": "Cleveland",
      "commonName": "Browns",
      "conf": "AFC",
      "div": "AFC North",
      "gp": 17,
      "w": 5,
      "l": 12,
      "t": 0,
      "winPct": 0.294,
      "pf": 279,
      "pa": 379,
      "pd": -100,
      "seed": 13,
      "score": 19,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
      "colors": {
        "primary": "#311d00",
        "secondary": "#ff3c00"
      }
    },
    {
      "code": "NYG",
      "city": "New York Giants",
      "shortName": "New York",
      "commonName": "Giants",
      "conf": "NFC",
      "div": "NFC East",
      "gp": 17,
      "w": 4,
      "l": 13,
      "t": 0,
      "winPct": 0.235,
      "pf": 381,
      "pa": 439,
      "pd": -58,
      "seed": 15,
      "score": 16,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
      "colors": {
        "primary": "#0b2265",
        "secondary": "#a71930"
      }
    },
    {
      "code": "ARI",
      "city": "Arizona Cardinals",
      "shortName": "Arizona",
      "commonName": "Cardinals",
      "conf": "NFC",
      "div": "NFC West",
      "gp": 17,
      "w": 3,
      "l": 14,
      "t": 0,
      "winPct": 0.176,
      "pf": 355,
      "pa": 488,
      "pd": -133,
      "seed": 16,
      "score": 8,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
      "colors": {
        "primary": "#97233f",
        "secondary": "#ffb612"
      }
    },
    {
      "code": "LV",
      "city": "Las Vegas Raiders",
      "shortName": "Las Vegas",
      "commonName": "Raiders",
      "conf": "AFC",
      "div": "AFC West",
      "gp": 17,
      "w": 3,
      "l": 14,
      "t": 0,
      "winPct": 0.176,
      "pf": 241,
      "pa": 432,
      "pd": -191,
      "seed": 14,
      "score": 5,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
      "colors": {
        "primary": "#000000",
        "secondary": "#a5acaf"
      }
    },
    {
      "code": "TEN",
      "city": "Tennessee Titans",
      "shortName": "Tennessee",
      "commonName": "Titans",
      "conf": "AFC",
      "div": "AFC South",
      "gp": 17,
      "w": 3,
      "l": 14,
      "t": 0,
      "winPct": 0.176,
      "pf": 284,
      "pa": 478,
      "pd": -194,
      "seed": 16,
      "score": 5,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
      "colors": {
        "primary": "#0c2340",
        "secondary": "#4b92db"
      }
    },
    {
      "code": "NYJ",
      "city": "New York Jets",
      "shortName": "New York",
      "commonName": "Jets",
      "conf": "AFC",
      "div": "AFC East",
      "gp": 17,
      "w": 3,
      "l": 14,
      "t": 0,
      "winPct": 0.176,
      "pf": 300,
      "pa": 503,
      "pd": -203,
      "seed": 15,
      "score": 5,
      "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
      "colors": {
        "primary": "#125740",
        "secondary": "#000000"
      }
    }
  ],
  "PLAYERS": [],
  "BRACKET": {
    "afc": {
      "wc": [],
      "div": [],
      "conf": []
    },
    "nfc": {
      "wc": [],
      "div": [],
      "conf": []
    },
    "sb": [
      {
        "hi": null,
        "lo": null,
        "winner": null,
        "seriesScore": "-"
      }
    ]
  },
  "HISTORY_PLAYERS": [
    {
      "rank": 1,
      "name": "Tom Brady",
      "pos": "QB",
      "teamCode": "NE",
      "era": "2000-22",
      "score": 100.0,
      "note": "7 Super Bowls · 5 SB MVP · GOAT indiscutible"
    },
    {
      "rank": 2,
      "name": "Peyton Manning",
      "pos": "QB",
      "teamCode": "IND",
      "era": "1998-15",
      "score": 96.0,
      "note": "5 MVP · 2 Super Bowls · cerebro ofensivo"
    },
    {
      "rank": 3,
      "name": "Joe Montana",
      "pos": "QB",
      "teamCode": "SF",
      "era": "1979-94",
      "score": 94.0,
      "note": "4 Super Bowls · 3 SB MVP · 'Joe Cool'"
    },
    {
      "rank": 4,
      "name": "Patrick Mahomes",
      "pos": "QB",
      "teamCode": "KC",
      "era": "2017-present",
      "score": 93.0,
      "note": "3 Super Bowls · 2 MVP · leyenda en construcción"
    },
    {
      "rank": 5,
      "name": "Johnny Unitas",
      "pos": "QB",
      "teamCode": "BAL",
      "era": "1956-73",
      "score": 92.5,
      "note": "3 títulos · pionero del juego aéreo moderno"
    },
    {
      "rank": 6,
      "name": "Brett Favre",
      "pos": "QB",
      "teamCode": "GB",
      "era": "1991-10",
      "score": 92.0,
      "note": "3 MVP · Super Bowl XXXI · récord de durabilidad"
    },
    {
      "rank": 7,
      "name": "Aaron Rodgers",
      "pos": "QB",
      "teamCode": "GB",
      "era": "2005-present",
      "score": 91.5,
      "note": "4 MVP · Super Bowl XLV · precisión histórica"
    },
    {
      "rank": 8,
      "name": "Drew Brees",
      "pos": "QB",
      "teamCode": "NO",
      "era": "2001-20",
      "score": 91.0,
      "note": "Super Bowl XLIV · récords de yardas y completados"
    },
    {
      "rank": 9,
      "name": "John Elway",
      "pos": "QB",
      "teamCode": "DEN",
      "era": "1983-98",
      "score": 90.5,
      "note": "2 Super Bowls · 'The Drive' · brazo legendario"
    },
    {
      "rank": 10,
      "name": "Dan Marino",
      "pos": "QB",
      "teamCode": "MIA",
      "era": "1983-99",
      "score": 90.0,
      "note": "MVP · récords de pase de su era (sin anillo)"
    }
  ],
  "ROAD_TO_GLORY": {
    "playerThreshold": 90.0,
    "players": [],
    "youngProspects": []
  },
  "DIVISIONS": [
    "AFC East",
    "AFC North",
    "AFC South",
    "AFC West",
    "NFC East",
    "NFC North",
    "NFC South",
    "NFC West"
  ],
  "SEASON": "2025",
  "SEASON_STATUS": "offseason",
  "IMPORTANCE": 3.0,
  "LAST_UPDATE": "2026-08-01 14:10 UTC",
  "SOURCE": {
    "name": "ESPN API",
    "baseUrl": "site.api.espn.com"
  }
};
