// Auto-generated 2026-09-01 23:24 UTC
window.SUMO_DATA = {
  "UPDATED": "2026-09-01 23:24 UTC",
  "LEGENDS": [
    {
      "id": "hakuho",
      "name": "Hakuho",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 100.0,
      "stats": {
        "yusho": 45,
        "yokozuna_basho": 84,
        "birth": 1985,
        "yok_start": 2007,
        "yok_end": 2021
      },
      "prevRank": 1
    },
    {
      "id": "taiho",
      "name": "Taiho",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 70.8,
      "stats": {
        "yusho": 32,
        "yokozuna_basho": 58,
        "birth": 1940,
        "yok_start": 1961,
        "yok_end": 1971
      },
      "prevRank": 2
    },
    {
      "id": "chiyonofuji",
      "name": "Chiyonofuji",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 68.9,
      "stats": {
        "yusho": 31,
        "yokozuna_basho": 58,
        "birth": 1955,
        "yok_start": 1981,
        "yok_end": 1991
      },
      "prevRank": 3
    },
    {
      "id": "asashoryu",
      "name": "Asashoryu",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 58.1,
      "stats": {
        "yusho": 25,
        "yokozuna_basho": 60,
        "birth": 1980,
        "yok_start": 2003,
        "yok_end": 2010
      },
      "prevRank": 4
    },
    {
      "id": "kitanoumi",
      "name": "Kitanoumi",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 56.7,
      "stats": {
        "yusho": 24,
        "yokozuna_basho": 63,
        "birth": 1953,
        "yok_start": 1974,
        "yok_end": 1985
      },
      "prevRank": 5
    },
    {
      "id": "musashimaru",
      "name": "Musashimaru",
      "country": "USA",
      "logo": "https://flagcdn.com/24x18/us.png",
      "teamCode": "USA",
      "primary": "#B22234",
      "secondary": "#FFFFFF",
      "legendScore": 29.6,
      "stats": {
        "yusho": 12,
        "yokozuna_basho": 38,
        "birth": 1971,
        "yok_start": 1999,
        "yok_end": 2003
      },
      "prevRank": 6
    },
    {
      "id": "futabayama",
      "name": "Futabayama",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 29.0,
      "stats": {
        "yusho": 12,
        "yokozuna_basho": 35,
        "birth": 1912,
        "yok_start": 1936,
        "yok_end": 1943
      },
      "prevRank": 7
    },
    {
      "id": "akebono",
      "name": "Akebono",
      "country": "USA",
      "logo": "https://flagcdn.com/24x18/us.png",
      "teamCode": "USA",
      "primary": "#B22234",
      "secondary": "#FFFFFF",
      "legendScore": 27.3,
      "stats": {
        "yusho": 11,
        "yokozuna_basho": 36,
        "birth": 1969,
        "yok_start": 1993,
        "yok_end": 2001
      },
      "prevRank": 8
    },
    {
      "id": "harumafuji",
      "name": "Harumafuji",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 22.5,
      "stats": {
        "yusho": 9,
        "yokozuna_basho": 30,
        "birth": 1984,
        "yok_start": 2012,
        "yok_end": 2017
      },
      "prevRank": 9
    },
    {
      "id": "terunofuji",
      "name": "Terunofuji",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 22.1,
      "stats": {
        "yusho": 10,
        "yokozuna_basho": 18,
        "birth": 1991,
        "yok_start": 2021,
        "yok_end": 2024
      },
      "prevRank": 10
    },
    {
      "id": "kakuryu",
      "name": "Kakuryu",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 19.1,
      "stats": {
        "yusho": 6,
        "yokozuna_basho": 42,
        "birth": 1985,
        "yok_start": 2014,
        "yok_end": 2021
      },
      "prevRank": 11
    },
    {
      "id": "onosato",
      "name": "Onosato",
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "teamCode": "JPN",
      "primary": "#BC002D",
      "secondary": "#FFFFFF",
      "legendScore": 10.5,
      "stats": {
        "yusho": 5,
        "yokozuna_basho": 6,
        "birth": 2000,
        "yok_start": 2025,
        "yok_end": null
      },
      "prevRank": 12
    },
    {
      "id": "hoshoryu",
      "name": "Hoshoryu",
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "teamCode": "MGL",
      "primary": "#C4272F",
      "secondary": "#FFFFFF",
      "legendScore": 7.1,
      "stats": {
        "yusho": 3,
        "yokozuna_basho": 8,
        "birth": 1999,
        "yok_start": 2024,
        "yok_end": null
      },
      "prevRank": 13
    }
  ],
  "BASHO_ID": "202609",
  "BASHO_INFO": {
    "id": "202609",
    "startDate": "2026-09-13T00:00:00Z",
    "endDate": "2026-09-27T00:00:00Z",
    "winner": null
  },
  "BANZUKE": [
    {
      "side": "East",
      "rankValue": 101,
      "rankLabel": "Yokozuna 1 East",
      "name": "Onosato",
      "rikishiID": 8850,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Yokozuna",
      "yusho": 5,
      "legendScore": 10.5,
      "age": 26,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 101,
      "rankLabel": "Yokozuna 1 West",
      "name": "Hoshoryu",
      "rikishiID": 19,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Yokozuna",
      "yusho": 3,
      "legendScore": 7.1,
      "age": 27,
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "primary": "#C4272F"
    },
    {
      "side": "East",
      "rankValue": 201,
      "rankLabel": "Ozeki 1 East",
      "name": "Kirishima",
      "rikishiID": 7,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Ozeki",
      "yusho": 3,
      "legendScore": 5.6,
      "age": 30,
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "primary": "#C4272F"
    },
    {
      "side": "West",
      "rankValue": 201,
      "rankLabel": "Ozeki 1 West",
      "name": "Kotozakura",
      "rikishiID": 20,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Ozeki",
      "yusho": 1,
      "legendScore": 1.9,
      "age": 28,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 202,
      "rankLabel": "Ozeki 2 East",
      "name": "Aonishiki",
      "rikishiID": 8854,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Ozeki",
      "yusho": 3,
      "legendScore": 5.6,
      "age": 22,
      "country": "UKR",
      "logo": "https://flagcdn.com/24x18/ua.png",
      "primary": "#4a4745"
    },
    {
      "side": "East",
      "rankValue": 301,
      "rankLabel": "Sekiwake 1 East",
      "name": "Atamifuji",
      "rikishiID": 74,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Sekiwake",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 23,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 301,
      "rankLabel": "Sekiwake 1 West",
      "name": "Fujinokawa",
      "rikishiID": 615,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Sekiwake",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 21,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 401,
      "rankLabel": "Komusubi 1 East",
      "name": "Hakunofuji",
      "rikishiID": 3,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Komusubi",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 23,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 401,
      "rankLabel": "Komusubi 1 West",
      "name": "Daieisho",
      "rikishiID": 9,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Komusubi",
      "yusho": 1,
      "legendScore": 1.9,
      "age": 32,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 501,
      "rankLabel": "Maegashira 1 East",
      "name": "Kotoshoho",
      "rikishiID": 8,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 1",
      "yusho": 1,
      "legendScore": 1.9,
      "age": 27,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 501,
      "rankLabel": "Maegashira 1 West",
      "name": "Kotoeiho",
      "rikishiID": 112,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 1",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 23,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 502,
      "rankLabel": "Maegashira 2 East",
      "name": "Takayasu",
      "rikishiID": 44,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 2",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 36,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 502,
      "rankLabel": "Maegashira 2 West",
      "name": "Yoshinofuji",
      "rikishiID": 8857,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 2",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 25,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 503,
      "rankLabel": "Maegashira 3 East",
      "name": "Gonoyama",
      "rikishiID": 56,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 3",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 28,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 503,
      "rankLabel": "Maegashira 3 West",
      "name": "Churanoumi",
      "rikishiID": 71,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 3",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 33,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 504,
      "rankLabel": "Maegashira 4 East",
      "name": "Takanosho",
      "rikishiID": 37,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 4",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 31,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "West",
      "rankValue": 504,
      "rankLabel": "Maegashira 4 West",
      "name": "Fujiryoga",
      "rikishiID": 9051,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 4",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 23,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    },
    {
      "side": "East",
      "rankValue": 505,
      "rankLabel": "Maegashira 5 East",
      "name": "Roga",
      "rikishiID": 55,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 5",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 27,
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "primary": "#C4272F"
    },
    {
      "side": "West",
      "rankValue": 505,
      "rankLabel": "Maegashira 5 West",
      "name": "Oshoma",
      "rikishiID": 61,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 5",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 29,
      "country": "MGL",
      "logo": "https://flagcdn.com/24x18/mn.png",
      "primary": "#C4272F"
    },
    {
      "side": "East",
      "rankValue": 506,
      "rankLabel": "Maegashira 6 East",
      "name": "Asanoyama",
      "rikishiID": 2,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "rankShort": "Maegashira 6",
      "yusho": 0,
      "legendScore": 0.0,
      "age": 32,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D"
    }
  ],
  "YOUNG_PROSPECTS": [
    {
      "id": "aonishiki",
      "name": "Aonishiki",
      "rankShort": "Ozeki",
      "age": 22,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "yusho": 3,
      "country": "UKR",
      "logo": "https://flagcdn.com/24x18/ua.png",
      "primary": "#4a4745",
      "projectedScore": 92.5
    },
    {
      "id": "fujinokawa",
      "name": "Fujinokawa",
      "rankShort": "Sekiwake",
      "age": 21,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "yusho": 0,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D",
      "projectedScore": 82.0
    },
    {
      "id": "atamifuji",
      "name": "Atamifuji",
      "rankShort": "Sekiwake",
      "age": 23,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "yusho": 0,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D",
      "projectedScore": 79.0
    },
    {
      "id": "hakunofuji",
      "name": "Hakunofuji",
      "rankShort": "Komusubi",
      "age": 23,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "yusho": 0,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D",
      "projectedScore": 71.0
    },
    {
      "id": "kotoeiho",
      "name": "Kotoeiho",
      "rankShort": "Maegashira 1",
      "age": 23,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "yusho": 0,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D",
      "projectedScore": 63.0
    },
    {
      "id": "yoshinofuji",
      "name": "Yoshinofuji",
      "rankShort": "Maegashira 2",
      "age": 25,
      "wins": 0,
      "losses": 0,
      "absences": 0,
      "yusho": 0,
      "country": "JPN",
      "logo": "https://flagcdn.com/24x18/jp.png",
      "primary": "#BC002D",
      "projectedScore": 57.0
    }
  ],
  "IMPORTANCE": 8.0
};
